import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./hydration-debug";
import HydrationProvider from "./HydrationProvider";
import ToastProvider from "../context/toastProvider";
import AlertProvider from "../context/alertProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ToastProvider>
          <AlertProvider>
          <HydrationProvider>
            {children}
          </HydrationProvider>
          </AlertProvider>
        </ToastProvider>
      </body>
    </html>
  );
}